### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by fipro78** [ECF/ServiceRegistry#1]
Hi,

after following the discussion in this blog [1] I tried out your ServiceRegistry. From the first tests I have to admit that it works pretty fine. I tested it with DS, EventAdmin, ConfigurationAdmin and the Gogo Shell using Felix.

I noticed that the classes all have the EPL header, but the project itself is missing a license. Do you publish this ServiceRegistry under the EPL? And if so, could you please add a license file on project level?

[1] https://tomsondev.bestsolution.at/2015/11/09/bringing-osgi-ds-to-plain-java-applications/

**Comment by scottslewis** [comment]
Hi fipro78

I've added a LICENSE.txt file to the ServiceRegistry projects.  I've used the EPL 1.0 for the time being.

> after following the discussion in this blog [1] I tried out your ServiceRegistry. From the first tests I have to admit that it works pretty fine. I tested it with DS, EventAdmin, ConfigurationAdmin and the Gogo Shell using Felix.

Thanks for the testing.  Perhaps you would want to contribute these tests to the project?   I would welcome additional tests with  standard OSGi services (I've also tried with SCR/DS and it works fine, but having more tests is better, and it's great to hear ConfigurationAdmin, EventAdmin, and Gogo shell all seem to work well).   In any event, it would be terrific if you would consider contributing.

Thanks.

**Comment by fipro78** [comment]
Thanks! To be honest, I had a hard time to get it running. Mainly for understanding the startup from within the IDE. You provided a launch configuration that works well, but I was not able to setup the same for my small sample easily. Probably because my knowledge of creating launch scripts is not that good. But it was easy to run when having the projects exported as JARs and start them from the console.

I definitely want to give back my lessons learned, I'm just not sure how and where. I planned to write a blog post series on declarative services and wanted to write one blog post at the end that shows how to run the whole sample (DS, EventAdmin, ConfigurationAdmin, Shell) with plain Java aswell.

If you have an idea how to contribute that to this project aswell, let me know.

**Comment by scottslewis** [comment]
> Thanks! To be honest, I had a hard time to get it running. Mainly for understanding the startup from >within the IDE. You provided a launch configuration that works well, but I was not able to setup the >same for my small sample easily. Probably because my knowledge of creating launch scripts is not >that good. But it was easy to run when having the projects exported as JARs and start them from the >console.

If you are willing, I would be completely happy with having scripts (e.g. ant/gradle/maven) that would create jars and possibly even create shell scripts for launching (i.e. with some set of bundles on classpath).   I think this would make things a lot easier for people to consume and use with or without Eclipse.

As for how and where... if you like we could create a new project...e.g. org.eclipse.ecf.serviceregistry.releng to put build scripts, etc.   

I would also very much appreciate a blog post...perhaps connected to some of my recent blog posts about ECF/Remote Services/etc at http://eclipseecf.blogspot.com

If you would like to chat/discuss...here or elsewhere please let me know.

**Comment by fipro78** [comment]
I will see what I am able to provide. But I agree that some build scripts
would be quite helpful. Just give me some time to get around.
Am 10.05.2016 19:35 schrieb "Scott Lewis" notifications@github.com:
